### ISSUE TITLE
搜索不到：AviatorScript

### ISSUE THREAD

**Issue by teaey** [yanchangyou/aviatorscript-ideaplugin#1]

**Comment by yanchangyou** [comment]
还在审批中，预览版下载：https://plugins.jetbrains.com/plugin/download?rel=true&updateId=101257

**Comment by yanchangyou** [comment]
审批已通过， 搜索【AviatorScript 】下载

**Comment by teaey** [comment]
还是搜索不到，下载的也无法安装

**Comment by yanchangyou** [comment]
你是使用IDEA最新预览版么？暂时不支持， 只支持 IDEA 2020.2.X以下版本； 最新版本API有调整， 不兼容 ，后面处理
