### ISSUE TITLE
请添加对最新版idea的支持

### ISSUE THREAD

**Issue by zhang13690** [yanchangyou/aviatorscript-ideaplugin#2]

**Comment by binggo-top** [comment]
求求了，拜托了，辛苦了~

**Comment by yanchangyou** [comment]
已提交，审批中

**Comment by binggo-top** [comment]
老哥神速，老哥牛批！！

**Comment by yanchangyou** [comment]
等不及的兄弟使用：直接下载
https://plugins.jetbrains.com/files/15303/131970/aviatorscript-ideaplugin-2021.2.zip

> 老哥神速，老哥牛批！！

**Comment by zhang13690** [comment]
> 等不及的兄弟使用：直接下载
> https://plugins.jetbrains.com/files/15303/131970/aviatorscript-ideaplugin-2021.2.zip
> 
> > 老哥神速，老哥牛批！！

还是不行。
![image](https://user-images.githubusercontent.com/12806078/130067241-ea3b5144-4530-4169-af6f-9f56a9677a41.png)

**Comment by yanchangyou** [comment]
> > 等不及的兄弟使用：直接下载
> > https://plugins.jetbrains.com/files/15303/131970/aviatorscript-ideaplugin-2021.2.zip
> > > 老哥神速，老哥牛批！！
> 
> 还是不行。
> ![image](https://user-images.githubusercontent.com/12806078/130067241-ea3b5144-4530-4169-af6f-9f56a9677a41.png)

IDEA使用的是什么版本？

**Comment by zhang13690** [comment]
@yanchangyou 用的是目前最新版的2021.2。

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
内部版本号 #IU-212.4746.92，July 27, 2021 构建
Licensed to IntelliJ IDEA Evaluator
到期日期: September 1, 2021
运行时版本: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Non-Bundled Plugins: com.intellij.zh (212.231), io.zhile.research.ide-eval-resetter (2.2.2), GrepConsole (11.10.211.6086.0), MyBatisLog (2021.5.1), ink.organics.pojo2json (1.0.11), MavenRunHelper (4.13.203.000.0), com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (2.9.3-183-204)
Kotlin: 212-1.5.10-release-IJ4746.92
```

**Comment by yanchangyou** [comment]
> @yanchangyou 用的是目前最新版的2021.2。
> 
> ```
> IntelliJ IDEA 2021.2 (Ultimate Edition)
> 内部版本号 #IU-212.4746.92，July 27, 2021 构建
> Licensed to IntelliJ IDEA Evaluator
> 到期日期: September 1, 2021
> 运行时版本: 11.0.11+9-b1504.13 amd64
> VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 750M
> Cores: 12
> Non-Bundled Plugins: com.intellij.zh (212.231), io.zhile.research.ide-eval-resetter (2.2.2), GrepConsole (11.10.211.6086.0), MyBatisLog (2021.5.1), ink.organics.pojo2json (1.0.11), MavenRunHelper (4.13.203.000.0), com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (2.9.3-183-204)
> Kotlin: 212-1.5.10-release-IJ4746.92
> ```

用这个
https://plugins.jetbrains.com/files/15303/133732/aviatorscript-ideaplugin-5.2.6-2021.08.21-IDEA.212.zip?updateId=133732&pluginId=15303&family=INTELLIJ

**Comment by zhang13690** [comment]
这次可以了！
希望完善下功能，就是我选中脚本语句执行“Run Aviator”命令的时候，能自动把“AviatorScript Console”面板展示出来。
否则第一次运行的时候没有展示出面板，给人的感觉好像插件没作用似的。
谢谢！

**Comment by yanchangyou** [comment]
> 这次可以了！
> 希望完善下功能，就是我选中脚本语句执行“Run Aviator”命令的时候，能自动把“AviatorScript Console”面板展示出来。
> 否则第一次运行的时候没有展示出面板，给人的感觉好像插件没作用似的。
> 谢谢！

单独开一个issue，这个先关闭了

**Comment by yanchangyou** [comment]
已审核通过，可以正常下载
