### ISSUE TITLE
不支持IDEA 2021.3.1 版本

### ISSUE THREAD

**Issue by zhang13690** [yanchangyou/aviatorscript-ideaplugin#5]
不支持新版本
IntelliJ IDEA 2021.3.1 (Ultimate Edition)

Build #IU-213.6461.79, built on December 29, 2021

**Comment by yanchangyou** [comment]
正在审批中， 预览版下载
 https://plugins.jetbrains.com/files/15303/153327/aviatorscript-ideaplugin-5.3.0-2022.01.11-IDEA.213.zip

**Comment by yanchangyou** [comment]
> 不支持新版本 IntelliJ IDEA 2021.3.1 (Ultimate Edition)
> 
> Build #IU-213.6461.79, built on December 29, 2021

正在审批中， 预览版下载
 https://plugins.jetbrains.com/files/15303/153327/aviatorscript-ideaplugin-5.3.0-2022.01.11-IDEA.213.zip

**Comment by zhang13690** [comment]
👍新版本可以使用了
