### ISSUE TITLE
gradle task myBuildPlugin 构建失败

### ISSUE THREAD

**Issue by wuguipeng** [yanchangyou/aviatorscript-ideaplugin#6]
> Task :compileJava FAILED
/Users/wuguipeng/Github.localized/aviatorscript-ideaplugin/src/main/java/my/lang/highlight/MyLanguageSyntaxHighlighterFactory.java:3: 错误: 无法访问SyntaxHighlighter
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
                                     ^
  错误的类文件: /Users/wuguipeng/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2021.3/75777e10a0e2880bc02945066dda2480a696c3d9/ideaIC-2021.3/lib/platform-api.jar(com/intellij/openapi/fileTypes/SyntaxHighlighter.class)
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by wuguipeng** [comment]
从jdk8 升级到jdk11 就没问题

**Comment by yanchangyou** [comment]
新版本已更新
